name: myenv
channels:
  - conda-forge
dependencies:
  - appnope=0.1.3=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bzip2=1.0.8=h3422bc3_4
  - ca-certificates=2022.12.7=h4653dfc_0
  - comm=0.1.3=pyhd8ed1ab_0
  - debugpy=1.6.7=py310h0f1eb42_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - executing=1.2.0=pyhd8ed1ab_0
  - importlib-metadata=6.4.1=pyha770c72_0
  - importlib_metadata=6.4.1=hd8ed1ab_0
  - ipykernel=6.22.0=pyh736e0ef_0
  - ipython=8.12.0=pyhd1c38e8_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jupyter_client=8.2.0=pyhd8ed1ab_0
  - jupyter_core=5.3.0=py310hbe9552e_0
  - libcxx=16.0.1=h75e25f2_0
  - libffi=3.4.2=h3422bc3_5
  - libsodium=1.0.18=h27ca646_1
  - libsqlite=3.40.0=h76d750c_0
  - libzlib=1.2.13=h03a7124_4
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.3=h07bb92c_1
  - nest-asyncio=1.5.6=pyhd8ed1ab_0
  - openssl=3.1.0=h03a7124_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.1=pyhd8ed1ab_0
  - platformdirs=3.2.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.38=pyha770c72_0
  - prompt_toolkit=3.0.38=hd8ed1ab_0
  - psutil=5.9.4=py310h8e9501a_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.15.0=pyhd8ed1ab_0
  - python=3.10.10=h3ba56d0_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-slugify=8.0.1=pyhd8ed1ab_0
  - python_abi=3.10=3_cp310
  - pyzmq=25.0.2=py310hc407298_0
  - readline=8.2=h92ec313_1
  - setuptools=67.6.1=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - text-unidecode=1.3=py_0
  - tk=8.6.12=he1e0b03_0
  - tornado=6.2=py310h8e9501a_1
  - traitlets=5.9.0=pyhd8ed1ab_0
  - typing-extensions=4.5.0=hd8ed1ab_0
  - typing_extensions=4.5.0=pyha770c72_0
  - unidecode=1.3.6=pyhd8ed1ab_0
  - wcwidth=0.2.6=pyhd8ed1ab_0
  - wheel=0.40.0=pyhd8ed1ab_0
  - xz=5.2.6=h57fd34a_0
  - zeromq=4.3.4=hbdafb3b_1
  - zipp=3.15.0=pyhd8ed1ab_0
  - pip:
      - certifi==2022.12.7
      - charset-normalizer==3.1.0
      - clip==0.2.0
      - contourpy==1.0.7
      - cycler==0.11.0
      - filelock==3.11.0
      - fonttools==4.39.3
      - idna==3.4
      - jinja2==3.1.2
      - kiwisolver==1.4.4
      - markupsafe==2.1.2
      - matplotlib==3.7.1
      - mpmath==1.3.0
      - networkx==3.1
      - numpy==1.24.2
      - pandas==2.0.0
      - pillow==9.5.0
      - pyparsing==3.0.9
      - python-dotenv==1.0.0
      - pytz==2023.3
      - requests==2.28.2
      - sympy==1.11.1
      - torch==2.0.0
      - torchvision==0.15.1
      - tzdata==2023.3
      - urllib3==1.26.15
prefix: /opt/homebrew/Caskroom/miniforge/base/envs/myenv
